### PR TITLE
[master] Mergebot Automated Train PR - 2019-Mar-22-16-56

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #248 - Update README.md

### CODE REVIEW

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot sync

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Comment by cprovencher** [comment]
@mesosphere-mergebot sync

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status dcos/dcos/changes.md DCOS-52807

**Pull request closed without merging**
